name: Test Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print UTC & KST
        run: |
          echo "✅ UTC Time: $(date -u)"
          echo "✅ KST Time: $(TZ=Asia/Seoul date)"
